-------------------------------------------------------------------------------
-- Mob Framework Mod by Sapier
-- 
-- You may copy, use, modify or do nearly anything except removing this
-- copyright notice. 
-- And of course you are NOT allow to pretend you have written it.
--
--! @file template.lua
--! @brief template file for movement patterns
--! @copyright Sapier
--! @author Sapier
--! @date 2012-08-11
--
--! @addtogroup mpatterns
--! @{
-- Contact sapier a t gmx net
-------------------------------------------------------------------------------
--movement pattern for movement generator
--	{
--      --patternname           
--      name                            ="example"
--
--		--chance to jump to higher level instead of turning
--		jump_up							=0,
--
--		--chance an mob does random jumps
--      random_jump_chance              =0,
--		--mobs jump speed (controling height of jump)
--      random_jump_initial_speed       =0,
--      --minimum time between random jumps
--      random_jump_delay               =0,
--      
--      --chance an mob randomly changes its speed/direction
--      random_acceleration_change      =0,
-- }

--!@}