local c_air = minetest.get_content_id("air")
local c_morstone = minetest.get_content_id("lottitems:mordor_stone")
local c_red_stone = minetest.get_content_id("lottitems:red_stone")
local c_desertsand = minetest.get_content_id("lottitems:desert_sand")
local c_dessandstone = minetest.get_content_id("lottitems:desert_sandstone")
local c_frozenstone = minetest.get_content_id("lottmapgen:frozen_stone")
local c_stone = minetest.get_content_id("lottitems:stone")
local c_dirt = minetest.get_content_id("lottitems:dirt")
local c_sand = minetest.get_content_id("lottitems:sand")
local c_sandstone = minetest.get_content_id("lottitems:sandstone")
local c_silsand = minetest.get_content_id("lottitems:silver_sand")
local c_gravel = minetest.get_content_id("lottitems:gravel")
local c_darkgravel = minetest.get_content_id("lottitems:dark_gravel")
local c_snow = minetest.get_content_id("lottitems:snow_layer")
local c_snowblock = minetest.get_content_id("lottitems:snow")
local c_ithilgrass = minetest.get_content_id("lottmapgen:ithilien_grass")
local c_ice = minetest.get_content_id("lottitems:ice")
local c_bluestone = minetest.get_content_id("lottitems:blue_stone")
-------------------
local c_frozenstone = minetest.get_content_id("lottitems:stone")--"lottmapgen:frozen_stone")
-----------
local c_dryshrub = minetest.get_content_id("lottplants:dry_shrub")
local c_mountainshrub = minetest.get_content_id("lottplants:mountain_shrub")
local c_melon = minetest.get_content_id("lottplants:melon_wild")
local c_bomordor = minetest.get_content_id("lottplants:brambles_of_mordor")
local c_pilinehtar = minetest.get_content_id("lottplants:pilinehtar")
local c_mallos = minetest.get_content_id("lottplants:mallos")
local c_menelluin = minetest.get_content_id("lottplants:menelluin")
local c_sunflower = minetest.get_content_id("lottplants:sunflower")
local c_bluebell = minetest.get_content_id("lottplants:bluebell")
local c_morwat = minetest.get_content_id("lottmapgen:blacksource")
local c_mountain_grass = minetest.get_content_id("lottplants:mountain_grass")
local c_encyclia = minetest.get_content_id("lottplants:encyclia")
local c_black_tulip = minetest.get_content_id("lottplants:tulip_black")

local c_dessandstone_brick = minetest.get_content_id("lottitems:desert_sandstone_brick")
local c_sandstone_brick = minetest.get_content_id("lottitems:sandstone_brick")

-- Grasses
local c_base_grass = minetest.get_content_id("lottitems:base_grass")
local c_snowy_grass = minetest.get_content_id("lottitems:snowy_grass")
local c_blue_mountains_grass = minetest.get_content_id("lottitems:blue_mountains_grass")
local c_dunland_grass = minetest.get_content_id("lottitems:dunland_grass")
local c_gondor_grass = minetest.get_content_id("lottitems:gondor_grass")
local c_lorien_grass = minetest.get_content_id("lottitems:lorien_grass")
local c_fangorn_grass = minetest.get_content_id("lottitems:fangorn_grass")
local c_mirkwood_grass = minetest.get_content_id("lottitems:mirkwood_grass")
local c_rohan_grass = minetest.get_content_id("lottitems:rohan_grass")
local c_shire_grass = minetest.get_content_id("lottitems:shire_grass")
local c_iron_hills_grass = minetest.get_content_id("lottitems:iron_hills_grass")
local c_rhun_grass = minetest.get_content_id("lottitems:rhun_grass")
local c_ettenmoors_grass = minetest.get_content_id("lottitems:ettenmoors_grass")
local c_lindon_grass = minetest.get_content_id("lottitems:lindon_grass")
local c_eregion_grass = minetest.get_content_id("lottitems:eregion_grass")
local c_wilderland_grass = minetest.get_content_id("lottitems:wilderland_grass")
local c_minhiriath_grass = minetest.get_content_id("lottitems:minhiriath_grass")
local c_enedwaith_grass = minetest.get_content_id("lottitems:enedwaith_grass")
local c_arthedain_grass = minetest.get_content_id("lottitems:arthedain_grass")

