print(" Currency mod loading... ")
dofile(minetest.get_modpath("currency").."/craftitems.lua")
print("[Currency] Craft_items Loaded!")
dofile(minetest.get_modpath("currency").."/shop.lua")
print("[Currency] Shop Loaded!")
dofile(minetest.get_modpath("currency").."/barter.lua")
print("[Currency]  Barter Loaded!")
dofile(minetest.get_modpath("currency").."/safe.lua")
print("[Currency] Safe Loaded!")
dofile(minetest.get_modpath("currency").."/crafting.lua")
print("[Currency] Crafting Loaded!")
dofile(minetest.get_modpath("currency").."/income.lua")
print("[Currency] Income Loaded!")
