dofile(minetest.get_modpath("kelvar").."/Guards/npc/gondor_guard.lua")
dofile(minetest.get_modpath("kelvar").."/Guards/npc/rohan_guard.lua")
dofile(minetest.get_modpath("kelvar").."/Guards/npc/dwarven_guard.lua")
dofile(minetest.get_modpath("kelvar").."/Guards/npc/elven_guard.lua")
dofile(minetest.get_modpath("kelvar").."/Guards/npc/orc_guard.lua")
dofile(minetest.get_modpath("kelvar").."/Guards/npc/uruk_hai_guard.lua")